### ISSUE TITLE
Bug - Add failed wes_run to wes_run table.

### ISSUE THREAD

**Issue by yash-puligundla** [ga4gh/ga4gh-starter-kit-wes#38]
Errored wes runs should be added to the wes_run table. these runs should be returned in the /runs endpoint.

**Comment by vsmalladi** [comment]
Agreed

**Comment by arungk703** [comment]
Hi, I have checked the code and it looks fine, we can add wes_run to wes_run_table.

**Comment by yash-puligundla** [comment]
Thank you for bringing this to our attention. Closing this issue as it has been resolved as of version 0.3.2.

**Comment by arungk703** [comment]
You can assign me tasks, I am ready to do.
